### ISSUE TITLE
Add support for computed.struct

### ISSUE THREAD

**Issue by steelbrain** [mobxjs/mobx-react-lite#231] opened 2019-10-15 16:48 UTC
Currently `mobx-react-lite` methods behave with the default configuration of `computed`, would be nice to be able to configure them to behave like `computed.struct`.

This could be done by allowing consumers to specify options like `equals` to feed directly to the underlying `computed` calls.

**Comment by FredyC** [comment] 2019-10-15 17:16
Uh, if you mean `useComputed`, be advised it's deprecated and will be removed in 2.x (by the end of the week). Either way, the `mobx-react-lite` does not impose any restrictions on how or what you are supposed to use to construct your observables.

I will close this for now but try to elaborate more why do you think there should be something in this library. Keep in mind you can always do `const [comp] = React.useState(() => computed(...))`.

**Closed** 2019-10-15 17:16 UTC

**Comment by mweststrate** [comment] 2019-10-15 18:44
I think the issue is about `useLocalState(() => ({ get something()
{....}))`? It is true that `computed` is not configurable in that case, but
if you need more customization, it should suffice to call `observable`
yourself explicitly, which have these possibilities, e.g. `useLocalState(()
=> observable({ get something() { } }, { something: computed(options) }))`.
In other words, it can be composed by using the lower level abstractions.
