### ISSUE TITLE
Using monorepo with mobx@4

### ISSUE THREAD

**Issue by ananiy** [mobxjs/mobx-react-lite#294] opened 2020-07-13 08:54 UTC
I have 2 apps 

```
packages/apps
-- app1
---- mobx@4 # for ie 
---- mobx-react-lite # this have a devDependencies: `"mobx": "5.14.0"`
-- app2
---- mobx@5
---- mobx-react-lite
```

![image](https://user-images.githubusercontent.com/33290601/87285029-9dccd800-c529-11ea-924f-4af50a56e8b3.png)

cause:

![image](https://user-images.githubusercontent.com/33290601/87285255-e2587380-c529-11ea-868d-85f43b86638b.png)

**Comment by FredyC** [comment] 2020-07-13 09:46
Something wrong in your setup, `mobx-react-lite` has `peerDependency` on `mobx` and as such, it won't be installed. I recommending deleting `node_modules` and reinstalling.

**Comment by ananiy** [comment] 2020-07-13 10:06
> Something wrong in your setup, `mobx-react-lite` has `peerDependency` on `mobx` and as such, it won't be installed. I recommend deleting `node_modules` and reinstalling.

I already do it sometimes.

My solutation is: 

```json
{
  "scripts": {
    "postinstall": "rimraf node_modules/mobx-react-lite/node_modules"
  }
}
```

I think it's caused by `mobx-react-lite` set 'mobx' as a dependency, so when I using https://classic.yarnpkg.com/blog/2018/02/15/nohoist/ , `mobx-react-lite` install mobx@5 in it's node_modules, and think the version of mobx is 5,  but the version of mobx actual use is 4.

**Comment by FredyC** [comment] 2020-07-13 16:42
Once again, `mobx-react-lite` does not depend on `mobx`, it's the only peerDependency which is something like a recommendation, but it won't be installed.

Please, if you are able to reproduce problem repeatedly, setup repro where we can inspect the behavior.

**Comment by ananiy** [comment] 2020-07-14 07:57
> Once again, `mobx-react-lite` does not depend on `mobx`, it's the only peerDependency which is something like a recommendation, but it won't be installed.
> 
> Please, if you are able to reproduce problem repeatedly, setup repro where we can inspect the behavior.

[demo.zip](https://github.com/mobxjs/mobx-react-lite/files/4917308/demo.zip)

Thanks for your reply.

I made a demo for this issue, just unzip it and just execute `yarn && yarn start:app2` to start.

You can see the version of  `packages/apps/app2/node_modules/mobx-react-lite/node_modules/mobx` is `5.14.4`, because of [this dependency](https://github.com/mobxjs/mobx-react-lite/blob/master/package.json#L69).

**Comment by mweststrate** [comment] 2020-07-14 09:32
That is a devDependency and should not exist in your local checkout unless
you are installing packages by hand.

**Comment by FredyC** [comment] 2020-07-14 15:44
@ananiy I am not sure what outcome do you expect. Each app declares a different version of `mobx`. If you really need that, you need to `nohoist` that package itself, not the `lite` which can be common.

**Comment by ananiy** [comment] 2020-07-15 02:14
> @ananiy I am not sure what outcome do you expect. Each app declares a different version of `mobx`. One gets installed to root, other into the app folder. If you really need that, you need to `nohoist` that package itself so it stays in app folder, not the `lite` which can be common. If you keep both apps strictly separate and there is no code sharing that would use mobx itself, it should work just fine.

I tried `nohoist` `mobx` beginning, got the same result.

```json
{
  "workspaces": {
    "packages": [
      "packages/common",
      "packages/apps/*"
    ],
    "nohoist": [
      "**/mobx",
      "**/mobx/**"
    ]
  },
}
```

app1:
![image](https://user-images.githubusercontent.com/33290601/87495092-1eebb280-c683-11ea-8e35-1b84863c1ea6.png)

app2:
![image](https://user-images.githubusercontent.com/33290601/87495237-71c56a00-c683-11ea-84f3-d664eddae07d.png)

if I delete `app2/node_modules/mobx` folder, it will work.

maye it's a `yarn workspace` issue, I don't know why...

**Comment by FredyC** [comment] 2020-07-15 07:34
Again, what do you expect? You have two `mobx` versions and they need to be somewhere.

**Comment by ananiy** [comment] 2020-07-16 03:02
I want to run two apps without error: "TypeError: observable.observers.add is not a function".

The fact is, whatever I nohoist anything, or `mobx`, or `lite`, or both `mobx` and `lite`, it will get error above. 

You can try it, don't forget run `rm -rf **/node_modules` before `yarn` when changed `package.json`.

Thx~

**Comment by FredyC** [comment] 2020-07-16 06:18
That all nice, but that's the problem of your setup, not MobX as it doesn't have any dependency that would cause it.

I think I will close this discussion and I would advise you to take the issue to Yarn as it seems to be the culprit here indeed.

**Closed by FredyC** 2020-07-16 06:18 UTC
Labels: bug

**Comment by ananiy** [comment] 2020-07-16 06:26
> That all nice, but that's the problem of your setup, not MobX as it doesn't have any dependency that would cause it.
> 
> I think I will close this discussion and I would advise you to take the issue to Yarn as it seems to be the culprit here indeed.

Thx for your advise 👍
