### ISSUE TITLE
need support case of 'parent / childs render in the right order'

### ISSUE THREAD

**Issue by snadn** [mobxjs/mobx-react-lite#191] opened 2019-08-02 07:20 UTC
is there any plan to support case of 'parent / childs render in the right order' https://github.com/mobxjs/mobx-react-lite/blob/master/test/observer.test.tsx#L600

**Comment by FredyC** [comment] 2019-08-02 09:32
Well, those tests were basically copied over from `mobx-react` and for some reason, it's commented out. Chances are it's actually working, I don't know. Can you present some real use case with reproduction, please?

**Comment by snadn** [comment] 2019-08-02 09:39
@FredyC my use case is same with the test. when logout, user data become null, and the components use user data which only render when login and control by parent get error.

**Comment by FredyC** [comment] 2019-08-02 11:11
Sorry, I am not sure I follow. That test is somewhat weirdly written and doesn't make much sense to me. I tried to rewrite it and it seems to be working. Please tweak that sandbox to reproduce your specific issue.

https://codesandbox.io/s/stupefied-pascal-o6wew

**Comment by mweststrate** [comment] 2019-08-02 21:02
@snadn for verification purposes, you could check if the problem disappears when using observer through mobx-react (mobx-react repackages mobx-react-lite + more goodies, so the rest of the impl will stay the same)

Please note that this issue is a duplicate of #153, so most probably not fixed yet .

As work around, doing the following in your app code before rendering React for the first time should also fix it: 

```javascript
import { configure } from "mobx"
import { unstable_batchedUpdates  } from "react-dom" // or react-native

configure({ reactionScheduler: unstable_batchedUpdates })
```

[source](https://github.com/mobxjs/mobx-react/blob/master/src/index.js)

**Comment by snadn** [comment] 2019-08-03 00:49
@mweststrate thanks, I will check later. I use mobx-react and mobx-react-lite in my project. I came across this problem when I use mobx-react-lite, and no problem when use mobx-react.

**Comment by snadn** [comment] 2019-08-05 05:20
@FredyC I reproduced this problem with mobx@4.13.0 mobx-react-lite@1.4.1 and async action.
https://codesandbox.io/s/brave-khayyam-we8ds
It's ok with mobx@4.13.0 mobx-react@6.1.1.
https://codesandbox.io/s/awesome-merkle-08slt

**Comment by FredyC** [comment] 2019-08-05 05:26
Ok, thanks for repro, that confirms it's indeed duplicate of #153 so closing here.

**Closed by FredyC** 2019-08-05 05:26 UTC

**Comment by FredyC** [comment] 2019-08-05 05:29
Although, I don't follow the use case. It seems that when I remove that `setTimeout` from the action, it works just fine in both cases (without batchedUpdates). Can you please elaborate on what is the use case for delaying action?

**Comment by snadn** [comment] 2019-08-05 05:33
I need to send a request to the server before logout

**Comment by mweststrate** [comment] 2019-08-05 09:24
Without the setTimeout you'll leverage the react batch that one gets for
free by using react event handlers, so it is correct that that "fixes" the
issue.

Op ma 5 aug. 2019 07:33 schreef snadn <notifications@github.com>:
