### ISSUE TITLE
How to use "useImperativeHandle"

### ISSUE THREAD

**Issue by HowardTangHw** [mobxjs/mobx-react-lite#192] opened 2019-08-05 10:28 UTC
```js
// parent Comp
<Child
    ref={ref => (this.childRef= ref)}
 />
```
```js
let ChildComp: React.SFC<any> = (props, ref) => {
    useImperativeHandle(ref, () => ({
        focus: () => {
            return '123123';
        },
    }));
    return <div>demo</div>;
};
const Child= inject('RootStore')(
    observer(ChildComp, { forwardRef: true })
);
export default Child
````

when i console.log `this.childRef`,`focus`  not found

version:
```js
"mobx": "^4.9.2",
"mobx-react": "^5.4.4",
"mobx-react-lite": "^2.0.0-alpha.2",
"react": "^16.8.6",
```

**Comment by FredyC** [comment] 2019-08-05 10:57
Can you please prepare sandbox reproduction? It depends when you are console logging.

**Comment by HowardTangHw** [comment] 2019-08-05 12:46
@FredyC 
an example in the sandbox 
https://codesandbox.io/s/angry-volhard-t9fe7?fontsize=14

**Comment by FredyC** [comment] 2019-08-05 13:14
Ok, thanks for repro. Turns out the naughty boy (or girl?) here is `inject` which doesn't handle `forwardRef` correctly in the currently released version. However, fix is already present in master, it just wasn't published yet. At this point, you have to either wait or use master version if you know-how. Or avoid using `inject` _([which is obsolete](https://mobx-react.js.org/recipes-inject) anyway)_.

Btw, small tip, I recommend you to use `React.createRef` instead of that callback there ... https://reactjs.org/docs/refs-and-the-dom.html#creating-refs

@xaviergonz @ItamarShDev Can one of you cut a release soon, please?

Closing as solved

**Closed by FredyC** 2019-08-05 13:14 UTC

**Comment by HowardTangHw** [comment] 2019-08-05 15:19
@FredyC 
I use mobx@5 because my project has to support ie
-------------------------------------------------------------
Anyway  thank you for your help & advice, Cheers!

**Comment by FredyC** [comment] 2019-08-05 15:22
The version of MobX doesn't matter.

**Comment by HowardTangHw** [comment] 2019-08-20 13:54
Hi, @FredyC ,I'm sorry to bother you.
I have a problem. I hope I can get your help

[React js createRef() show typescript error](https://stackoverflow.com/questions/57571903/react-js-createref-show-typescript-error)
