### ISSUE TITLE
Rendered fewer hooks than expected with new React Native fast refresh. 0.61

### ISSUE THREAD

**Issue by drewhamlett** [mobxjs/mobx-react-lite#226] opened 2019-09-27 02:51 UTC
If you create a new react native project on 0.61, and create a component wrapped with observer HOC, you get an error when hot reloading(fast refresh).  The <Observer> component seems to work fine(which would make sense).  Everything else seems good with useLocalStore and others.  Just wanted to bring it up incase others are running into it.  Unfortunately I can't get anything to run online.  Snack doesn't support latest react native.  I'd be glad to walk someone through it or create a project if needed.  Thanks!

https://facebook.github.io/react-native/blog/2019/09/18/version-0.61

**Comment by FredyC** [comment] 2019-09-27 06:33
Can you at least make some screenshot & show call stack of mentioned error? The hot reloading was always problematic and I wouldn't be surprised if it would be RN problem considering it's a fresh new feature.

And you can also try mobx-react-lite@next which includes experimental improvements regarding Concurrent mode if that could help in any way.

**Comment by drewhamlett** [comment] 2019-09-27 11:55
Sure, it doesn't give a trace to mobx-react-lite though.  This is with mobx-react-lite@2.0.0-alpha.2.  The first fast refresh works fine.  It's after that it stops working and you get this.

<img width="478" alt="Screen Shot 2019-09-27 at 7 54 06 AM" src="https://user-images.githubusercontent.com/1056587/65767481-ff879700-e0fb-11e9-9a3f-c6fc74287928.png">

**Comment by FredyC** [comment] 2019-09-27 12:36
Sorry, but until proven it's actually a problem of this library, I am going to close this. Doesn't really sound like the case considering it works in React.

**Comment by drewhamlett** [comment] 2019-09-27 12:41
@FredyC  Is fast refresh available in React on web?  I think it's only React Native for now.

**Comment by mweststrate** [comment] 2019-09-27 12:55
It is RN only indeed

Op vr 27 sep. 2019 13:41 schreef Drew Hamlett <notifications@github.com>:

**Comment by drewhamlett** [comment] 2019-09-28 14:29
Could @FredyC be confusing hot reloading which works with mobx-react with fast refresh which is currently not working?

**Comment by FredyC** [comment] 2019-09-28 15:05
It doesn't really matter how is it called or how it works, but it's likely that fast refresh is a culprit here considering its fresh new feature and given there is no mention of mobx in the stack trace.

**Comment by bolandrm** [comment] 2019-10-03 16:58
I'm experiencing the same issue.  The problem stops when I change:

```
export default observer(SignInScreen)
```

to:

```
export default SignInScreen
``` 

Also using RN fast refresh.

**Comment by FredyC** [comment] 2019-10-03 17:26
I would generally recommend waiting for dust from fast refresh to settle. Obviously, it's a new thing and as such it will have quirks and issues. If you are impatient, try to file the issue with RN and if they actually find the problem is on MobX side, we can do changes, but until then there is no point in posting comments here.

**Comment by drewhamlett** [comment] 2019-10-05 16:33
I did some more testing just trying different versions of observer.

```import { Reaction } from 'mobx'
import React, { useState, useEffect, useMemo, useRef } from 'react'

export function observer<P>(
  baseComponent: React.FunctionComponent<P>,
): React.FunctionComponent<P> {
  return React.memo((props) => {
    // forceUpdate 2.0
    const forceUpdate = useForceUpdate()

    const reaction = useRef<Reaction | null>(null)
    if (!reaction.current) {
      reaction.current = new Reaction(`observer`, () => {
        forceUpdate()
      })
    }

    // clean up the reaction if this component is unMount
    // useUnmount(() => reaction.current.dispose())

    // render the original component, but have the
    // reaction track the observables, so that rendering
    // can be invalidated (see above) once a dependency changes
    let rendering
    reaction.current.track(() => {
      rendering = baseComponent(props)
    })
    return rendering
  })
}

function useForceUpdate() {
  const [, setTick] = useState(1)
  return () => {
    setTick((c) => c + 1)
  }
}

function useUnmount(fn) {
  useEffect(() => fn, [])
}
```
It seems to work if I don't dispose of the reaction.

**Comment by FredyC** [comment] 2019-10-05 16:55
I wouldn't be surprised if "fast refresh" would be doing something unnatural to a component lifecycle. We definitely want to keep reaction cleanup :) Besides, in 2.0 this is expanded to support Concurrent mode, so if fast refresh does something out of books, then they have to fix it. Have you actually tried to file an issue with RN about this?

**Comment by gaearon** [comment] 2019-10-12 13:28
I think the notion that Fast Refresh is broken is a bit of a hasty conclusion. We've been using it at Facebook since June so it's pretty stable. If someone can take the Mobx source code, copy paste it into the project, and then remove things until we have a minimal reproducing state, I can look closer.

**Comment by gaearon** [comment] 2019-10-12 13:31
One thing that's worth keeping in mind is that Fast Refresh will "free" `useMemo` and `useCallback`, and it will re-run all effects once. If you rely on `useMemo` and `useCallback` as semantics guarantees, don't — there are other things beyond Fast Refresh that can break this in the future (for example, a built-in virtualization solution).

**Comment by FredyC** [comment] 2019-10-12 14:43
The `useMemo` or `useCallback` is not a problem here for sure. Rerunning effects could in theory cause "something", but I cannot imagine why would React complain with that specific error message. There are no conditionals in running hooks so it feels like that error is false positive 🤷‍♂ 

@drewhamlett @Jakst Can you please prepare that repro? It's been a while since I've fiddled with RN and I don't particularly want to dive in it again.

**Comment by bolandrm** [comment] 2019-10-12 16:02
Here's a minimal example with the relevant mobx/mobx-react-lite code copied into the project:

https://github.com/bolandrm/rn-mobx-fast-reload-example

The mobx code could probably be minimized more, but i'm not sure if that's as important as the mobx-react-lite code (which i've minimized).

A few notes:

1.  to reproduce, reload the javascript and then save a javascript file 2 times.  It reproduces 100% of the time after the 2nd save.
1.  i've completely eliminated `useCallback` and the behavior persists.
1.  changing `  const memoComponent = memo(wrappedComponent);` ->  `  const memoComponent = wrappedComponent;`  causes the error to not occur anymore.

**Comment by FredyC** [comment] 2019-10-12 18:42
@bolandrm Thanks a lot, those are interesting findings, especially no. 3. I find it hard to believe it would be something against rules. I mean I am sure other HOCs want to introduce such optimization too.

Either way, as I noted above, can you please grab the [`useObserver` from `next` branch](https://github.com/mobxjs/mobx-react-lite/blob/next/src/useObserver.ts) as it's more polished toward the Concurrent mode.

**Comment by gaearon** [comment] 2019-10-12 20:18
Thanks for a minimal repro. I will be looking at this on Monday.

**Comment by drewhamlett** [comment] 2019-10-14 13:26
Thanks for getting that @bolandrm .  The other thing that's happening

If there are no hooks:  The second save with fast refresh, the component doesn't render anything.

**Comment by gaearon** [comment] 2019-10-14 14:41
I haven't managed to run the repro project yet. I'm stuck at this:

<img width="581" alt="Screen Shot 2019-10-14 at 3 41 15 PM" src="https://user-images.githubusercontent.com/810438/66759958-13bbea00-ee99-11e9-8717-2570a59b8c41.png">

**Comment by drewhamlett** [comment] 2019-10-14 14:44
```
yarn install
cd ios && pod install
react-native run-ios
```
?

If you open the project in Xcode to run make sure you open the workspace, not the project. 
react-native run-ios will do the right thing though

**Comment by gaearon** [comment] 2019-10-14 14:49
OK I had no idea I needed to run `pod install`, RN didn't tell me that :P

**Comment by gaearon** [comment] 2019-10-14 14:55
Looking at `useObserver`, this code:

```js
  let rendering;
  console.log('render 1')
  reaction.current.track(() => {
    console.log('inside track 1')
    rendering = fn();
  });
```

sometimes logs `render 1` without `inside track 1`.

Is that expected? Does `reaction.current.track` guarantee its argument to be insta-called or not?

**Comment by gaearon** [comment] 2019-10-14 14:56
OK right that behavior makes sense. As I mentioned in https://github.com/mobxjs/mobx-react-lite/issues/226#issuecomment-541325283, Fast Refresh will re-run effects on every change. Re-running effects causes mobx to dispose of the reaction. So it doesn't execute the inner function anymore, causing no hooks to be called on next render.

**Comment by gaearon** [comment] 2019-10-14 15:00
One way you could fix this is by nulling out `reaction.current` in `dispose`:

<img width="672" alt="Screen Shot 2019-10-14 at 4 00 24 PM" src="https://user-images.githubusercontent.com/810438/66761357-c0976680-ee9b-11e9-8e43-8bc49b06bd07.png">

Then the first `if (!reaction.current) {` check will be true on next render, and the reaction will be re-created on demand.

**Comment by FredyC** [comment] 2019-10-14 15:19
Well, we do have quite elaborate cleanup routines in the `next` branch and we are already doing that.

https://github.com/mobxjs/mobx-react-lite/blob/bd54c8cb7e608d1cfeb6ece41d118dee04e48848/src/useObserver.ts#L61

Back then we have fairly elaborate discussion on the topic of cleanup - https://github.com/facebook/react/issues/15317. So I suppose the next step is to actually try the reproduction with full code of that `useObserver`, but @drewhamlett already mentioned he tried it and it did not work either.

**Comment by gaearon** [comment] 2019-10-14 15:22
Is the fix I proposed insufficient and has some other issues?

**Comment by gaearon** [comment] 2019-10-14 15:22
What I mean is it should be possible to get this change out to fix Fast Refresh experience without blocking it on the rest of the `next` changes.

**Comment by FredyC** [comment] 2019-10-14 15:24
@gaearon No, point is that "next" should be already fixed by your comment but based on https://github.com/mobxjs/mobx-react-lite/issues/226#issuecomment-535908518 there is no point in doing it in the "master".

**Comment by FredyC** [comment] 2019-10-14 15:26
Besides, we are planning to release 2.0 fairly soon, so I would be more interested in fixing it there than in the "master". We don't plan to support 1.0 after that.

**Comment by mweststrate** [comment] 2019-10-14 15:26
@FredyC not sure if I follow your proposal. Landing this specific change as patch on master and release it seems to be a lot less obtrusive than waiting until the entire next version is released, or do I misunderstand you?

**Comment by gaearon** [comment] 2019-10-14 15:31
So this is only relevant to 2.0 alpha and not to 1.x? If it's a one line fix and it affects 1.x, it would still be nice to get it out because this experience reflects badly on Fast Refresh itself, and shakes confidence in the feature.

**Comment by FredyC** [comment] 2019-10-14 15:31
PR made and if tests will pass, it can go out. But I still would like to know if "next" work. Can someone try that, please? And if not, we will need to update reproduction to use that code and hopefully, @gaearon can have another look.

**Comment by gaearon** [comment] 2019-10-14 15:32
@FredyC Can you make a PR to the repro repo to use code from `@next`? I can look at that!

**Comment by FredyC** [comment] 2019-10-14 15:34
Sorry, I am fairly busy myself. Hopefully one of the guys from here can manage that.

**Comment by FredyC** [comment] 2019-10-14 15:37
Version 1.4.2 with the change published.

**Comment by drewhamlett** [comment] 2019-10-14 15:38
Just to confirm again.  next published on npm does not work.  rendered fewer hooks than expected and blank render without a hook.

**Comment by drewhamlett** [comment] 2019-10-14 15:43
Latest version (1.4.2) working 😄 .  Thanks so much for the work!  I never thought I would see everyone on this.  I didn't post on react-native because I thought they would blame Mobx and then Mobx would blame react-native and it would never go anywhere.  This is definitely awesome.

**Comment by mweststrate** [comment] 2019-10-14 15:44
@FredyC I don't think you looked into mobx-react yet did you? If you did, let me know, otherwise I'll cut a release for that one tonight as well with this patch.

**Comment by FredyC** [comment] 2019-10-14 15:56
@mweststrate Published mobx-react@6.1.4 with updated dependency.

**Comment by mweststrate** [comment] 2019-10-14 15:57
Such fast. Thanks Daniel!
![183889a5a9f62bbbf0ae76f75f08a604538b0cce8f351a4e1e1da45255050910](https://user-images.githubusercontent.com/1820292/66765375-b24d4880-eea3-11e9-942c-69b0fc7c1f44.jpg)

**Comment by FredyC** [comment] 2019-10-14 15:58
Let's keep this open though until the "next" is figured out.

**Comment by FredyC** [comment] 2019-10-15 02:38
Kudos to @normano64 for spotting that the same is probably [missing from "next"](https://github.com/mobxjs/mobx-react-lite/pull/212#discussion_r334659190). I've cut a new alpha release `2.0.0-alpha.3`. Can someone please test it out in RN and let me know?

I also wonder if some kind of test can be written for this scenario. To be honest, I did not fully understand what's the problem here. If someone does, PR with a test to the "next" branch is definitely welcome.

**Comment by gaearon** [comment] 2019-10-15 13:30
>To be honest, I did not fully understand what's the problem here

Fast Refresh will re-run all effects when a component's file is edited, *including the ones marked with `[]`*. If you think about it, that's the only way changes to effects' source code can propagate.

What happened was:

* MobX disposes of the Reaction in its `[]` cleanup handler. It assumes `[]` cleanup executes only on unmount.
* Fast Refresh re-runs all effects, including the `[]` one. This means that we clean up the "previous" effect and set it up again.
  - This disposes the Reaction.
* During rendering, we call `reaction.current.track`. Remember, this Reaction was just disposed of. So MobX [ignores this call](https://github.com/mobxjs/mobx/blob/4d22593dde33dcd7631e2c18f922c270e7f525ec/src/core/reaction.ts#L122-L123) and doesn't call the inner function.
  - As a result, our rendering function with a `useState` Hook doesn't get called.
  - As a result, we have a mismatching number of Hooks between renders.

The fix was to null out the Reaction. This ensures that on next render, the same logic that *initially* created a React, *creates it again* (because it's `null`). So we get a new Reaction to work with, and MobX uses it.

**Comment by mweststrate** [comment] 2019-10-15 14:39
Thanks @gaearon, this explanation is super helpful

**Comment by FredyC** [comment] 2019-10-24 03:58
So, no hero is going to be found who can test the `next` branch for this issue? I will release it by the start of the week and 1.x will become obsolete so if it doesn't work, we might end up in a similar dance like before in here.

**Comment by FredyC** [comment] 2020-02-16 17:11
Closing this for now. The 2.0 won't be coming out that soon yet as we need to investigate how it will work with true Concurrent mode.

**Closed by FredyC** 2020-02-16 17:11 UTC

**Comment by Gaafar** [comment] 2020-03-05 04:02
@FredyC I tested the release `2.0.0-alpha.3` with React Native `0.61.5` and it seems to be working as expected in my case.

Here's what I'm testing:
* enable fast refresh
* update an observer component
* check if the component is still observing the store and able to call actions

Is there a way this fix can be cherrypicked without waiting for 2.0?

**Comment by FredyC** [comment] 2020-03-05 07:46
@Gaafar Uh, the 1.x should be working as well ... https://github.com/mobxjs/mobx-react-lite/issues/226#issuecomment-541755589. Nothing has changed since then.

**Comment by Gaafar** [comment] 2020-03-06 17:13
Oh, but it's not working in my case. Let me see if I can create an example to reproduce
