### ISSUE TITLE
Can not update state from a class component

### ISSUE THREAD

**Issue by tjoskar** [mobxjs/mobx-react-lite#144] opened 2019-05-01 11:53 UTC
Let's say we have a mobx store like this:

```ts
import { observable } from "mobx";

const data = observable({
  myNumber: 0,

  set1() {
    console.log("Changing mynumber to 1!");
    this.myNumber = 1;
  },

  set2() {
    console.log("Changing mynumber to 2!");
    this.myNumber = 2;
  },

  set3() {
    console.log("Changing mynumber to 3!");
    this.myNumber = 3;
  }
})
```

And using it like this:
```ts
const MyComponent = observer(() => {
  useEffect(() => {
    setTimeout(() => data.set1(), 1000);
    setTimeout(() => data.set2(), 2000);
  }, []);
  return <p>{data.myNumber}</p>;
});

render(<MyComponent />, document.getElementById("root"));
```

This will work fine but if a create a class component and change the store inside like this:
```ts
class Wrapper extends React.Component {
  componentDidMount() {
    data.set3();
  }

  render() {
    return this.props.children
  }
}
```
and then use it:
```ts
render(<Wrapper><MyComponent /></Wrapper>, document.getElementById("root"));
```
It does not work any more. I do not get any errors and the only number that are printed is the default one (0 in this case). So the component `MyComponent` is never rerended but if I create a reaction: `reaction(() => data.myNumber, myNumber => console.log(myNumber))` it get every change. 

If I rewrite `Wrapper` to a function component, `MyComponent` will rerender:
```ts
const Wrapper = ({ children }) => {
  useEffect(() => data.set3())
  return children;
}
```

Is this intended?

I created a code sandbox to easier explain the bug/issue. https://codesandbox.io/s/qxy8qwp4l6

Thanks!

**Comment by FredyC** [comment] 2019-05-01 12:47
I don't follow. I've tried your example, you not even rendering the functional `Wrapper2` and yet the output in console is as it should be. What is not working actually? :)

```
Changing mynumber to 3! 
myNumber: 3 
Changing mynumber to 1! 
myNumber: 1 
Changing mynumber to 2! 
myNumber: 2 
```

**Comment by tjoskar** [comment] 2019-05-01 14:14
@FredyC, Yeah sorry. It is kind of hard to explain. 
The console does print the expected output but the component does not rerender. 

In my example above the DOM never change (It always print `My Component 0`) **BUT** it you [remove line number 39](https://codesandbox.io/s/znxm0kk97p) (`data.set3();`) the DOM output changes **OR** if you [use the the functional `Wrapper2`](https://codesandbox.io/s/lll3jlz25l) the DOM output change as well.

In the example above (https://codesandbox.io/s/qxy8qwp4l6) you can see that the store changes it value in the console but the component to not react. Why is that? It works if I don't change the store value in the Wrapper component or if the Wrapper component is a function. I did not expect that behavior.

**Comment by tjoskar** [comment] 2019-05-01 14:18
I expect that when the console prints `myNumber: 1` the component output should change to `My Component 1`

**Comment by FredyC** [comment] 2019-05-01 14:35
Oh, I see, you are right, something wonky is happening there. Honestly, I don't know what's happening there. I was never using classes that much in React.

Either way, it's easily fixable by using observer `mobx-react` V6 which is in alpha right now. It uses lite package underneath so it is also compatible with hooks, but it does some extra mile for class components. Perhaps @mweststrate might be able to give a better explanation of the problem.

**Comment by meyer** [comment] 2019-05-01 20:48
@FredyC I think this is related to the 1.3.0 release

**Comment by meyer** [comment] 2019-05-01 20:58
I’ve simplified the example down a bit and made the number change repeat so the effect (no pun intended) is more pronounced.

https://codesandbox.io/embed/52rq0kz59p

Works fine with `mobx-react-lite@1.2.0` (you can change the version in the left-hand sidebar), fails with `mobx-react-lite@1.3.0`.

1.3.0:

![mobx-react-lite 1 3 0](https://user-images.githubusercontent.com/13781/57042303-2313e780-6c19-11e9-9920-047311264278.gif)

1.2.0:

![mobx-react-lite 1 2 0](https://user-images.githubusercontent.com/13781/57042319-2e671300-6c19-11e9-86e0-51c0691c8c29.gif)

**Comment by FredyC** [comment] 2019-05-01 21:00
Yea, you are right, with `mobx-react-lite@test` it's fixed as well. Good catch! :) It's great we have an example here, although a fairly strange one. I still don't understand why rendering children with class component would behave differently than doing it from a function component.

**Comment by meyer** [comment] 2019-05-01 21:13
the super weird thing is that if you comment out the `this.myNumber = 69` line in the example I posted, the bug does not occur.

**Comment by urugator** [comment] 2019-05-02 10:37
The problem is that `componentDidUpdate` runs *before* the [effect sets the commited flag](https://github.com/mobxjs/mobx-react-lite/blob/v1.3.0/src/useObserver.ts#L43), therefore the [scheduled reaction is ignored](https://github.com/mobxjs/mobx-react-lite/blob/v1.3.0/src/useObserver.ts#L35).
It does not happen with `Wrapper2`, because it's effect runs *after* `MyComponent`'s effects (after the commited flag is set).

**Comment by FredyC** [comment] 2019-05-02 10:40
Well, there is a `componentDidMount`, not update, but I suppose it's the same problem. Would be great if someone can submit a test case PR to cover this.

**Comment by urugator** [comment] 2019-05-02 10:41
I meant mount ... sorry fixed

**Comment by mweststrate** [comment] 2019-05-02 12:11
cc: @RoystonS ideas?

**Comment by FredyC** [comment] 2019-05-02 13:49
@mweststrate No need to worry about it, this was because of accidentally released #119. The proper solution from #121 is in the `mobx-react-lite@next` so I reverted that experiment and published 1.3.1. It works with that. I would just like to have a test case covering for it so we can avoid in the future.

**Comment by RoystonS** [comment] 2019-05-02 17:26
Just to test I've caught up correctly, 1.3.0 was released with PR #119, and has problems, whereas @next contains PR #119 and #121 and works ok?

**Comment by RoystonS** [comment] 2019-05-02 17:27
In that case, I think the tests I added for #121 _may_ have covered the problems with #119. There were certainly some tests I specifically added to #121 because of problems in #119.

**Comment by FredyC** [comment] 2019-05-02 18:51
@RoystonS Ah, that makes sense. The `@next` was built on top of 1.3.0, so that should be ok.

I am not sure if anyone actually tried `@next` except you :) I haven't really advertised anywhere, not sure where and how. It will probably sit there for a while, maybe till more people start experimenting with StrictMode.

**Closed** 2019-05-02 18:52 UTC
Labels: bug
